Authorization
MariannaHanina/vue3sendbox pull request #21
Opened 2021-10-05 15:01 UTC by MariannaHanina

2021-10-05 17:12 UTC, DogFox requested changes

2021-10-05 17:12 UTC, DogFox commented on src/layouts/DsnLayoutManager/DsnLayoutManager.spec.ts
> +      (isAuthenticated as jest.Mock).mockImplementation(() => true);
Об этом ты говорила, в контексте тестирования mounted?

2021-10-05 17:12 UTC, DogFox commented on src/modules/auth/store.ts
> +      localStorage.setItem(LOCAL_STORAGE, token);
тут, по-хорошему, проверить бы то что пришло

2021-10-05 17:12 UTC, DogFox commented on src/modules/auth/store.ts
> +      apiHttp.manager.setAuthorizationHeader(token);
может тогда расширить класс, а не вводить сущность менеджера в одну большую?

2021-10-05 17:12 UTC, DogFox commented on src/modules/auth/utils.ts
> +function getToken (): string | undefined {
если функция не экспортится и используется только тут в одном месте, может не стоит ее выделять?

2021-10-06 06:15 UTC, MariannaHanina commented on src/layouts/DsnLayoutDefault/DsnLayoutDefault.vue
> +    <el-header class="bg-blue-100 grid grid-cols-2">
скорее всего, обычно шапка на сайте в единственном экземпляре. за разовость еще говорит то, что этот компонент используется именно в рамках лейаута страницы.

2021-10-06 06:20 UTC, MariannaHanina commented on src/layouts/DsnLayoutDefault/components/TopNav/TopNav.vue
> +    background-color="transparent"
это стандартное свойство данного компонента для задачи его бэкграунда - почему бы его не использовать?

2021-10-06 06:28 UTC, MariannaHanina commented on src/layouts/DsnLayoutManager/DsnLayoutManager.spec.ts
> +      (isAuthenticated as jest.Mock).mockImplementation(() => true);
чуть ниже, 55ая строка

2021-10-06 06:28 UTC, MariannaHanina commented on src/modules/auth/store.ts
> +      localStorage.setItem(LOCAL_STORAGE, token);
какого рода проверка бы тут подошла?

2021-10-06 06:28 UTC, MariannaHanina commented on src/modules/auth/store.ts
> +      apiHttp.manager.setAuthorizationHeader(token);
по поводу введения этой сущности, есть такой принцип проектирования - предпочитай композицию наследованию. В данном случае ещё и принцип единой ответственности не будет учтен, если это всё свалить в один суперкласс. Делать массивные классы с кучей разносортного функционала вообще плохая практика. Можем в живую ещё об этом подискутировать.

2021-10-06 06:28 UTC, MariannaHanina commented on src/modules/auth/utils.ts
> +function getToken (): string | undefined {
в данном случае я решила это обернуть в отдельную функцию, потому что есть такой принцип - изолируй то, что может измениться. Получение значения токина на мой взгляд - вполне может измениться со временем, так как возможно мы будет хранить его где-то в другом месте. Надо будет кстати и всю работу с локал сторадж тоже обернуть, это я забыла сделать.

2021-10-06 07:58 UTC, merged